[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.pdo_mysql",
  "php82Extensions.mbstring",
  "php82Extensions.openssl",
  "php82Extensions.bcmath",
  "php82Extensions.tokenizer",
  "php82Extensions.xml",
  "nodejs_18"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan key:generate",
  "php artisan migrate --force"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
